# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190124_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='images'),
        ),
    ]
