# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugcomment',
            name='author_status',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Staff'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
