# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190124_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_author_avatar',
            field=models.CharField(blank=True, default='images/user.jpg', max_length=200),
        ),
    ]
