# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-16 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190124_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='bug_author_avatar',
        ),
        migrations.RemoveField(
            model_name='bugcomment',
            name='author_avatar',
        ),
    ]
